### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-moor-tools-plugin#19]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte

Traceback (most recent call last):

  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\Project Selector\projectselector.py", line 119, in selectTemplate

    templateSelectorDlg = TemplateSelectorDialog(self.iface)

  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\Project Selector\templateselectordialog.py", line 90, in __init__

    self.onTemplateTypeChanged()

  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\Project Selector\templateselectordialog.py", line 182, in onTemplateTypeChanged

    self.loadCopyrights()

  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\Project Selector\templateselectordialog.py", line 317, in loadCopyrights

    defautlCopyright = defaultFile.read().strip()

  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\codecs.py", line 322, in decode

    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte

**Comment by erpas** [comment]
I have added decoding error handling for that default copyright file.

The file should contain a FILENAME of default copyrights, not the copyrights themselves.
In this particular case, the contents of `default.txt` file was:

`© Crown copyright...`

while it should contain name of one of the copyrights filenames for the template.
